# Generated by Django 3.2.13 on 2022-12-02 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=128)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code')),
            ],
            options={
                'verbose_name': 'house',
                'verbose_name_plural': 'house',
                'db_table': 'house',
            },
        ),
    ]
